name: yt_music
description: Unofficial YouTube Music Api for dart
version: 0.1.0
repository: https://github.com/sheikhhaziq/dart_ytmusic_api.git

environment:
  sdk: ^3.4.3

dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.5.0+1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.15
